services:
  localai:
    extends:
      file: docker-compose.yaml
      service: localai
    environment:
      - LOCALAI_SINGLE_ACTIVE_BACKEND=true
      - DEBUG=true
    image: localai/localai:master-gpu-hipblas
    devices:
      - /dev/dri
      - /dev/kfd

  dind:
    extends:
      file: docker-compose.yaml
      service: dind

  localrecall-postgres:
    extends:
      file: docker-compose.yaml
      service: localrecall-postgres

  localrecall:
    extends:
      file: docker-compose.yaml
      service: localrecall

  localrecall-healthcheck:
    extends:
      file: docker-compose.yaml
      service: localrecall-healthcheck

  localagi:
    extends:
      file: docker-compose.yaml
      service: localagi
