- id: huggingface@thebloke/gplatty-30b-ggml/gplatty-30b.ggmlv3.q2_k.bin
  name: "gpt-4"
  overrides: 
    context_size: 4096
    mmap: true
    f16: true
    mirostat: 2
    mirostat_tau: 5.0
    mirostat_eta: 0.1
    parameters: 
      temperature: 0.1
      top_k: 40
      top_p: 0.95
- id: model-gallery@stablediffusion
- id: model-gallery@voice-en-us-kathleen-low
- url: github:go-skynet/model-gallery/base.yaml
  name: all-MiniLM-L6-v2
  overrides:
    embeddings: true
    backend: huggingface-embeddings
    parameters:
      model: all-MiniLM-L6-v2
- id: huggingface@thebloke/gplatty-30b-ggml/gplatty-30b.ggmlv3.q2_k.bin
  name: functions
  overrides:
    context_size: 4096
    mirostat: 2
    mirostat_tau: 5.0
    mirostat_eta: 0.1
    template:
      chat: ""
      completion: ""
    roles:
      assistant: "ASSISTANT:"
      system: "SYSTEM:"
      assistant_function_call: "FUNCTION_CALL:"
      function: "FUNCTION CALL RESULT:"
    parameters:
      temperature: 0.1
      top_k: 40
      top_p: 0.95
    function:
      disable_no_action: true
    mmap: true
    f16: true